#!/usr/bin/env ruby

require 'rubygems'
require 'active_record'

Dir.chdir File.join(File.dirname(__FILE__), '..')

ActiveRecord::Base.logger = Logger.new("debug.log")

databases = YAML::load(IO.read("spec/db/database.yml"))
db_info = databases[ENV["DB"] || "test"]
ActiveRecord::Base.establish_connection(db_info)

load("spec/db/schema.rb")