#!/usr/bin/env ruby
Dir.chdir File.join(File.dirname(__FILE__), '..')
data = IO.read('spec/active_record/blueprints_spec.rb')

data.gsub!("require File.dirname(__FILE__) + '/spec_helper'", "require File.dirname(__FILE__) + '/test_helper'")
data.gsub!("describe Blueprints do", 'class BlueprintsTest < ActiveSupport::TestCase')

# lambda {
#   hornsby_clear :undo => :just_orange
# }.should raise_error(ArgumentError)
data.gsub!(/(\s+)lambda \{\n(.*)\n(\s+)\}.should raise_error\((.*)\)/, "\\1assert_raise(\\4) do\n\\2\n\\3end")
# .should_not => assert(!())
data.gsub!(/^(\s+)(.*)\.should_not(.*)/, '\1assert(!(\2\3))')
# .should => assert()
data.gsub!(/^(\s+)(.*)\.should(.*)/, '\1assert(\2\3)')
# be_nil => .nil?
data.gsub!(/ be_([^\(\)]*)/, '.\1?')
# have(2).items => .size == 2
data.gsub!(/ have\((\d+)\)\.items/, '.size == \1')

data.gsub!(/^(\s+)describe/, '\1context')
data.gsub!(/^(\s+)it (["'])(should )?/, '\1should \2')
data.gsub!(/^(\s+)before.*do/, '\1setup do')
data.gsub!(/^(\s+)after.*do/, '\1teardown do')

File.open('test/blueprints_test.rb', 'w') {|f| f.write(data)}
